# Generated by Django 4.2 on 2026-02-07 09:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0066_remove_product_epicentr_category'),
        ('categories', '0025_remove_category_epicentr_category'),
        ('attributes', '0022_alter_attributeinmodnakastacategory_attribute'),
        ('sizes', '0009_alter_sizegroup_grids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('integration_type', models.CharField(choices=[('xml_feed', 'XML Feed'), ('api', 'API Integration'), ('both', 'XML + API')], default='xml_feed', max_length=20, verbose_name='Тип интеграции')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='\n        Пример: {\n            "base_url": "https://api.epicentrm.com.ua",\n            "auth_type": "bearer",\n            "token": "xxx",\n            "endpoints": {\n                "categories": "/v2/pim/categories",\n                "attribute_sets": "/v2/pim/attribute-sets"\n            }\n        }\n        ', verbose_name='Конфигурация API')),
                ('feed_template', models.CharField(blank=True, help_text='Например: feed/epicentr/', max_length=255, verbose_name='Путь к шаблону фида')),
                ('feed_filename', models.CharField(blank=True, help_text='Например: epicentr.xml', max_length=100, verbose_name='Имя файла фида')),
                ('feed_url', models.URLField(blank=True, help_text='Публичный URL для доступа к фиду', verbose_name='URL фида')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_feed_generated', models.DateTimeField(blank=True, null=True, verbose_name='Последняя генерация фида')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=100, verbose_name='Код атрибута')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_uk', models.CharField(blank=True, max_length=255, verbose_name='Название (укр)')),
                ('attr_type', models.CharField(choices=[('select', 'Единичный выбор'), ('multiselect', 'Множественный выбор'), ('string', 'Строка'), ('text', 'Текст'), ('int', 'Целое число'), ('float', 'Дробное число'), ('boolean', 'Да/Нет'), ('array', 'Массив')], default='string', max_length=20, verbose_name='Тип')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный')),
                ('group_name', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('group_code', models.CharField(blank=True, max_length=100, verbose_name='Код группы')),
                ('suffix', models.CharField(blank=True, help_text='Например: мм, г', max_length=50, verbose_name='Суффикс')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
            ],
            options={
                'verbose_name': 'Атрибут маркетплейса',
                'verbose_name_plural': 'Атрибуты маркетплейсов',
                'ordering': ['-is_required', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=100, verbose_name='Код опции')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('name_uk', models.CharField(blank=True, max_length=500, verbose_name='Название (укр)')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='marketplaces.marketplaceattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Опция атрибута',
                'verbose_name_plural': 'Опции атрибутов',
                'ordering': ['name'],
                'unique_together': {('attribute', 'external_code')},
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID')),
                ('external_code', models.CharField(blank=True, max_length=100, verbose_name='Код категории')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('name_uk', models.CharField(blank=True, max_length=500, verbose_name='Название (укр)')),
                ('full_path', models.CharField(blank=True, max_length=1000, verbose_name='Полный путь')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Например: {"kind_id": 123, "affiliation_id": 456}', verbose_name='Доп. данные')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дочерние')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='marketplaces.marketplace', verbose_name='Маркетплейс')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplaces.marketplacecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория маркетплейса',
                'verbose_name_plural': 'Категории маркетплейсов',
                'ordering': ['name'],
                'unique_together': {('marketplace', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketplaceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('brand', 'Бренд'), ('country', 'Страна'), ('color', 'Цвет'), ('size', 'Размер'), ('measure', 'Единица измерения')], max_length=20, verbose_name='Тип сущности')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID')),
                ('external_code', models.CharField(blank=True, max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_uk', models.CharField(blank=True, max_length=255, verbose_name='Название (укр)')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='marketplaces.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Сущность маркетплейса',
                'verbose_name_plural': 'Сущности маркетплейсов',
                'ordering': ['entity_type', 'name'],
                'unique_together': {('marketplace', 'entity_type', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAttributeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=100, verbose_name='Код набора')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_uk', models.CharField(blank=True, max_length=255, verbose_name='Название (укр)')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_sets', to='marketplaces.marketplace', verbose_name='Маркетплейс')),
                ('marketplace_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_sets', to='marketplaces.marketplacecategory', verbose_name='Категория маркетплейса')),
            ],
            options={
                'verbose_name': 'Набор атрибутов',
                'verbose_name_plural': 'Наборы атрибутов',
                'ordering': ['name'],
                'unique_together': {('marketplace', 'external_code')},
            },
        ),
        migrations.AddField(
            model_name='marketplaceattribute',
            name='attribute_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='marketplaces.marketplaceattributeset', verbose_name='Набор атрибутов'),
        ),
        migrations.CreateModel(
            name='SizeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace_entity', models.ForeignKey(limit_choices_to={'entity_type': 'size'}, on_delete=django.db.models.deletion.CASCADE, related_name='size_mappings', to='marketplaces.marketplaceentity', verbose_name='Размер маркетплейса')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='sizes.size', verbose_name='Наш размер')),
            ],
            options={
                'verbose_name': 'Маппинг размера',
                'verbose_name_plural': 'Маппинги размеров',
                'unique_together': {('size', 'marketplace_entity')},
            },
        ),
        migrations.CreateModel(
            name='ProductMarketplaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('custom_name', models.CharField(blank=True, max_length=500, verbose_name='Кастомное название')),
                ('custom_name_uk', models.CharField(blank=True, max_length=500, verbose_name='Кастомное название (укр)')),
                ('custom_description', models.TextField(blank=True, verbose_name='Кастомное описание')),
                ('custom_description_uk', models.TextField(blank=True, verbose_name='Кастомное описание (укр)')),
                ('last_exported', models.DateTimeField(blank=True, null=True, verbose_name='Последний экспорт')),
                ('export_errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки экспорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_overrides', to='marketplaces.marketplacecategory', verbose_name='Переопределить категорию')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='marketplaces.marketplace', verbose_name='Маркетплейс')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_configs', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Настройки товара для маркетплейса',
                'verbose_name_plural': 'Настройки товаров для маркетплейсов',
                'unique_together': {('product', 'marketplace')},
            },
        ),
        migrations.CreateModel(
            name='ProductMarketplaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=1000, verbose_name='Значение (строка)')),
                ('value_text', models.TextField(blank=True, verbose_name='Значение (текст)')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Значение (целое)')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='Значение (дробное)')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Значение (да/нет)')),
                ('value_json', models.JSONField(blank=True, default=dict, verbose_name='Значение (JSON)')),
                ('value_string_uk', models.CharField(blank=True, max_length=1000, verbose_name='Значение (строка, укр)')),
                ('value_text_uk', models.TextField(blank=True, verbose_name='Значение (текст, укр)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='marketplaces.marketplaceattribute', verbose_name='Атрибут маркетплейса')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_attributes', to='product.product', verbose_name='Товар')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_product_values', to='marketplaces.marketplaceattributeoption', verbose_name='Значение (выбор)')),
                ('value_options', models.ManyToManyField(blank=True, related_name='multi_product_values', to='marketplaces.marketplaceattributeoption', verbose_name='Значения (множественный выбор)')),
            ],
            options={
                'verbose_name': 'Атрибут товара для маркетплейса',
                'verbose_name_plural': 'Атрибуты товаров для маркетплейсов',
                'unique_together': {('product', 'marketplace_attribute')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='marketplaceattribute',
            unique_together={('attribute_set', 'external_code')},
        ),
        migrations.CreateModel(
            name='CountryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='product.country', verbose_name='Наша страна')),
                ('marketplace_entity', models.ForeignKey(limit_choices_to={'entity_type': 'country'}, on_delete=django.db.models.deletion.CASCADE, related_name='country_mappings', to='marketplaces.marketplaceentity', verbose_name='Страна маркетплейса')),
            ],
            options={
                'verbose_name': 'Маппинг страны',
                'verbose_name_plural': 'Маппинги стран',
                'unique_together': {('country', 'marketplace_entity')},
            },
        ),
        migrations.CreateModel(
            name='ColorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='product.color', verbose_name='Наш цвет')),
                ('marketplace_entity', models.ForeignKey(limit_choices_to={'entity_type': 'color'}, on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='marketplaces.marketplaceentity', verbose_name='Цвет маркетплейса')),
            ],
            options={
                'verbose_name': 'Маппинг цвета',
                'verbose_name_plural': 'Маппинги цветов',
                'unique_together': {('color', 'marketplace_entity')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('custom_name', models.CharField(blank=True, help_text='Переопределить название категории для этого маркетплейса', max_length=255, verbose_name='Кастомное название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='categories.category', verbose_name='Наша категория')),
                ('marketplace_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='marketplaces.marketplacecategory', verbose_name='Категория маркетплейса')),
            ],
            options={
                'verbose_name': 'Маппинг категории',
                'verbose_name_plural': 'Маппинги категорий',
                'unique_together': {('category', 'marketplace_category')},
            },
        ),
        migrations.CreateModel(
            name='BrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='product.brand', verbose_name='Наш бренд')),
                ('marketplace_entity', models.ForeignKey(limit_choices_to={'entity_type': 'brand'}, on_delete=django.db.models.deletion.CASCADE, related_name='brand_mappings', to='marketplaces.marketplaceentity', verbose_name='Бренд маркетплейса')),
            ],
            options={
                'verbose_name': 'Маппинг бренда',
                'verbose_name_plural': 'Маппинги брендов',
                'unique_together': {('brand', 'marketplace_entity')},
            },
        ),
        migrations.CreateModel(
            name='AttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mappings', to='marketplaces.marketplaceattribute', verbose_name='Атрибут маркетплейса')),
                ('marketplace_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_mappings', to='marketplaces.marketplaceattributeoption', verbose_name='Опция маркетплейса')),
                ('our_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='attributes.attribute', verbose_name='Наш атрибут')),
            ],
            options={
                'verbose_name': 'Маппинг атрибута',
                'verbose_name_plural': 'Маппинги атрибутов',
                'unique_together': {('our_attribute', 'marketplace_attribute')},
            },
        ),
    ]
