# Generated by Django 4.2 on 2026-02-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('template_type', models.CharField(choices=[('header', 'Шапка (Header)'), ('product', 'Товар (Product)'), ('variant', 'Вариант (Variant)'), ('footer', 'Подвал (Footer)')], max_length=20, verbose_name='Тип шаблона')),
                ('content', models.TextField(help_text='Jinja2/Django template синтаксис', verbose_name='Содержимое шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_templates', to='marketplaces.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Шаблон фида',
                'verbose_name_plural': 'Шаблоны фидов',
                'ordering': ['marketplace', 'template_type'],
                'unique_together': {('marketplace', 'template_type')},
            },
        ),
    ]
