# Generated by Django 4.2 on 2026-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_add_feed_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacecategory',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внешний ID'),
        ),
    ]
