# Generated by Django 4.2 on 2026-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_allow_blank_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacecategory',
            name='external_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код категории'),
        ),
        migrations.AlterField(
            model_name='marketplacecategory',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID'),
        ),
    ]
