# Generated by Django 4.2 on 2026-02-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplaces', '0004_external_id_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting_input', 'Waiting for User Input'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='active', max_length=20)),
                ('context', models.JSONField(default=dict, help_text='Research findings: URLs, API structure, file formats, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Agent Conversation',
                'verbose_name_plural': 'Agent Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Global pipeline configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Marketplace Pipeline',
                'verbose_name_plural': 'Marketplace Pipelines',
                'ordering': ['-created_at'],
                'unique_together': {('marketplace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('download_file', 'Download File'), ('parse_xml', 'Parse XML Feed'), ('parse_json', 'Parse JSON'), ('parse_csv', 'Parse CSV'), ('sync_categories', 'Sync Categories'), ('sync_attributes', 'Sync Attribute Sets'), ('sync_options', 'Sync Attribute Options'), ('sync_entities', 'Sync Entities (brands, colors, etc.)'), ('api_call', 'API Call'), ('transform_data', 'Transform Data'), ('ai_process', 'AI Processing'), ('validate', 'Validate Data'), ('custom', 'Custom Handler')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict, help_text='Step-specific configuration')),
                ('is_enabled', models.BooleanField(default=True)),
                ('on_error', models.CharField(choices=[('stop', 'Stop pipeline'), ('skip', 'Skip and continue'), ('retry', 'Retry step')], default='stop', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('timeout', models.PositiveIntegerField(default=300, help_text='Timeout in seconds')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketplaces.marketplacepipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Step',
                'verbose_name_plural': 'Pipeline Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.JSONField(default=dict, help_text='Progress per step: {step_id: {status, result, error, duration}}')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_runs', to='marketplaces.pipelinestep')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='marketplaces.marketplacepipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pipeline_run', 'Pipeline Execution'), ('research_agent', 'AI Research'), ('sync_operation', 'Sync Operation'), ('file_download', 'File Download'), ('ai_processing', 'AI Processing')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Task input parameters')),
                ('result', models.JSONField(blank=True, help_text='Task output/result', null=True)),
                ('error', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('progress_message', models.CharField(blank=True, help_text='Current progress message', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Background Task',
                'verbose_name_plural': 'Background Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('question', 'Question requiring answer'), ('findings', 'Research findings'), ('progress', 'Progress update'), ('error', 'Error'), ('action', 'Action performed')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='URLs, options for user, structured data, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplaces.agentconversation')),
            ],
            options={
                'verbose_name': 'Agent Message',
                'verbose_name_plural': 'Agent Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['status', 'task_type'], name='marketplace_status_f4dbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['created_at'], name='marketplace_created_0cf415_idx'),
        ),
    ]
