# Generated by Django 4.2 on 2026-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0005_agentconversation_marketplacepipeline_pipelinestep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepipeline',
            name='purpose',
            field=models.CharField(choices=[('categories', 'Categories'), ('attributes', 'Attributes'), ('other', 'Other')], default='other', help_text='Pipeline purpose: categories, attributes, or other', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='step_type',
            field=models.CharField(choices=[('download_file', 'Download File'), ('parse_xml', 'Parse XML Feed'), ('parse_json', 'Parse JSON'), ('parse_csv', 'Parse CSV'), ('parse_xlsx', 'Parse XLSX/Excel'), ('sync_categories', 'Sync Categories'), ('sync_attributes', 'Sync Attribute Sets'), ('sync_options', 'Sync Attribute Options'), ('sync_entities', 'Sync Entities (brands, colors, etc.)'), ('api_call', 'API Call'), ('transform_data', 'Transform Data'), ('ai_process', 'AI Processing'), ('validate', 'Validate Data'), ('custom', 'Custom Handler')], max_length=50),
        ),
    ]
