# Generated by Django 4.2 on 2026-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0006_add_pipeline_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacepipeline',
            name='purpose',
            field=models.CharField(choices=[('categories', 'Categories'), ('attributes', 'Attributes'), ('attribute_options', 'Attribute Options'), ('other', 'Other')], default='other', help_text='Pipeline purpose: categories, attributes, or other', max_length=20),
        ),
    ]
