# Generated by Django 4.2.3 on 2026-03-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_remove_product_epicentr_category'),
        ('marketplaces', '0007_add_attribute_options_purpose'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmarketplaceattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productmarketplaceattribute',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_attributes', to='product.variant', verbose_name='Вариант'),
        ),
        migrations.AddField(
            model_name='productmarketplaceattribute',
            name='variant_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_attributes', to='product.variantsize', verbose_name='Размер варианта'),
        ),
        migrations.AlterUniqueTogether(
            name='productmarketplaceattribute',
            unique_together={('product', 'marketplace_attribute', 'variant', 'variant_size')},
        ),
        migrations.CreateModel(
            name='MarketplaceAttributeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('product', 'Товар'), ('variant', 'Вариант'), ('size', 'Размер'), ('brand', 'Бренд (авто)'), ('skip', 'Пропустить')], default='product', max_length=20, verbose_name='Уровень заполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_levels', to='marketplaces.categorymapping', verbose_name='Маппинг категории')),
                ('marketplace_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assignments', to='marketplaces.marketplaceattribute', verbose_name='Атрибут маркетплейса')),
            ],
            options={
                'verbose_name': 'Уровень атрибута маркетплейса',
                'verbose_name_plural': 'Уровни атрибутов маркетплейсов',
                'ordering': ['-marketplace_attribute__is_required', 'marketplace_attribute__name'],
                'unique_together': {('category_mapping', 'marketplace_attribute')},
            },
        ),
    ]
