# Generated by Django 4.2.3 on 2026-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0008_add_attribute_level_and_variant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceattributelevel',
            name='level',
            field=models.CharField(choices=[('product', 'Товар'), ('variant', 'Вариант'), ('size', 'Размер'), ('brand', 'Бренд (авто)'), ('color', 'Цвет (авто)'), ('country', 'Страна (авто)'), ('skip', 'Пропустить')], default='product', max_length=20, verbose_name='Уровень заполнения'),
        ),
    ]
