# Generated by Django 4.2.3 on 2026-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0009_add_country_level_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceattributelevel',
            name='level',
            field=models.CharField(choices=[('product', 'Товар'), ('variant', 'Вариант'), ('size', 'Размер'), ('brand', 'Бренд (авто)'), ('color', 'Цвет (авто)'), ('country', 'Страна (авто)'), ('composition', 'Состав ткани (авто)'), ('skip', 'Пропустить')], default='product', max_length=20, verbose_name='Уровень заполнения'),
        ),
    ]
