# Generated by Django 4.1.7 on 2023-04-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_attribute_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattributegroup',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
