# Generated by Django 4.1.7 on 2023-05-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categoryattributegroup_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'collections',
            },
        ),
    ]
