# Generated by Django 4.1.7 on 2023-05-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
    ]
