# Generated by Django 4.1.7 on 2023-05-06 11:02

import apps.abstract.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_collection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=apps.abstract.fields.DeletableImageField(blank=True, null=True, upload_to='collections', verbose_name='Изображение'),
        ),
    ]
