# Generated by Django 4.1.7 on 2023-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_producttranslation_language_code'),
        ('categories', '0007_collection_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collections',
        ),
    ]
