# Generated by Django 4.1.7 on 2023-05-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_rename_collection_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
