# Generated by Django 4.1.7 on 2023-06-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0004_alter_size_options_alter_sizegrid_options_and_more'),
        ('categories', '0010_categorytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_preferred_size_grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sizes.sizegrid', verbose_name='предпочтительная размерная сетка'),
        ),
    ]
