# Generated by Django 4.2 on 2023-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_rename_product_preferred_size_grid_category_preferred_size_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
    ]
