# Generated by Django 4.2 on 2023-08-28 16:21

import apps.abstract.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_alter_category_options_category_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=apps.abstract.fields.DeletableImageField(blank=True, null=True, upload_to='categories', verbose_name='Изображение'),
        ),
    ]
