# Generated by Django 4.2.4 on 2023-09-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_googletaxonomyuplaoder_filter_root'),
        ('categories', '0016_alter_categorytranslation_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='google_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.googletaxonomy', verbose_name='Google Taxonomy'),
        ),
    ]
