# Generated by Django 4.2.4 on 2023-10-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_alter_facebookcategories_facebook_id'),
        ('categories', '0017_category_google_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='facebook_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.facebookcategories', verbose_name='Facebook Category'),
        ),
    ]
