# Generated by Django 4.2.4 on 2023-11-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_modnakastacategories'),
        ('categories', '0018_category_facebook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modna_kast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.modnakastacategories', verbose_name='Категория ModnaKasta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='facebook_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.facebookcategories', verbose_name='Категория Facebook'),
        ),
    ]
