# Generated by Django 4.2.4 on 2023-12-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_alter_modnakastacategories_options_and_more'),
        ('categories', '0020_category_update_mk_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modna_kast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='integrations.modnakastacategories', verbose_name='Категория ModnaKasta'),
        ),
    ]
