# Generated by Django 4.2 on 2025-09-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_epicentrattributeset_epicentrcategories_and_more'),
        ('categories', '0022_category_auto_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='epicentr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.epicentrcategories', verbose_name='Категория Epicentr'),
        ),
    ]
