# Generated by Django 4.2 on 2025-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_category_mk_append_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='epicentr_category',
        ),
    ]
