FROM node:20-alpine

RUN npm install -g pm2

WORKDIR /app/frontend

COPY package.json yarn.lock ./
RUN npm install --legacy-peer-deps --production=false

COPY . .

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

RUN npm run build

EXPOSE 3000

CMD ["pm2-runtime", "start", "npm", "--", "run", "start"] 