version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    hostname: '0.0.0.0'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/data/dumps/:/docker-entrypoint-initdb.d
    expose:
      - 5432
    environment:
      - POSTGRES_HOST='0.0.0.0'
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moami_db
    ports:
      - 5432:5432

  cache:
    image: redis:alpine
    ports:
      - 6379:6379


volumes:
  postgres_data:
