import React from "react";
import Head from 'next/head'
import {Header} from "@/components/Shared/Header";
import {Content, Main} from "@/styles/Blocks/Content";
import CustomThemeProvider from "@/styles/ThemeProvider";
import {Breadcrumbs} from './Breadcrumbs'
import {Footer} from "@/components/Shared/Footer";

export interface BreadcrumbsState {
    title: string,
    link?: string
}

interface LayoutProps {
    children: React.ReactNode;
    breadcrumbs?: BreadcrumbsState[]
}

export default function Layout({children, breadcrumbs}: LayoutProps) {
    return <>
        <Head>
            <title>Moami</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <CustomThemeProvider>
            <Header/>
            <Main>
                <Content>
                    <Breadcrumbs breadcrumbs={breadcrumbs}/>
                </Content>
                <Content>
                    {children}
                </Content>
            </Main>
            <Footer/>
        </CustomThemeProvider>
    </>
}