# Generated by Django 4.1.7 on 2023-04-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPostApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewPostAreas',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('areas_center', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('description', 'description_ru'),
            },
        ),
        migrations.CreateModel(
            name='NewPostCities',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('settlement_type', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255)),
                ('description_translit', models.CharField(max_length=255)),
                ('settlement_type_description', models.CharField(max_length=255)),
                ('settlement_type_description_ru', models.CharField(max_length=255)),
                ('settlement_type_description_translit', models.CharField(max_length=255)),
                ('warehouse', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostareas')),
            ],
            options={
                'ordering': ('description', 'description_ru'),
            },
        ),
        migrations.CreateModel(
            name='NewPostRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255)),
                ('description_translit', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostareas')),
            ],
            options={
                'ordering': ('description', 'description_ru'),
            },
        ),
        migrations.CreateModel(
            name='NewPostDepartments',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=0)),
                ('site_key', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255)),
                ('short_address', models.CharField(max_length=255)),
                ('short_address_ru', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('schedule', models.JSONField(default=dict)),
                ('receiving_limitations_on_dimensions', models.JSONField(default=dict)),
                ('place_max_weight_allowed', models.PositiveIntegerField(default=0)),
                ('warehouse_status', models.CharField(max_length=255)),
                ('warehouse_index', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='newpost.newpostcities')),
            ],
            options={
                'ordering': ('number', 'description', 'description_ru'),
            },
        ),
        migrations.AddField(
            model_name='newpostcities',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostregion'),
        ),
    ]
