# Generated by Django 4.2 on 2023-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpostapikey',
            options={'verbose_name': 'Ключ Новой почты', 'verbose_name_plural': '1. Ключ Новой почты'},
        ),
        migrations.AlterModelOptions(
            name='newpostareas',
            options={'ordering': ('description', 'description_ru'), 'verbose_name': 'Область', 'verbose_name_plural': '2. Области'},
        ),
        migrations.AlterModelOptions(
            name='newpostcities',
            options={'ordering': ('description', 'description_ru'), 'verbose_name': 'Город', 'verbose_name_plural': '4. Города'},
        ),
        migrations.AlterModelOptions(
            name='newpostdepartments',
            options={'ordering': ('number', 'description', 'description_ru'), 'verbose_name': 'Отделение', 'verbose_name_plural': '5. Отделения'},
        ),
        migrations.AlterModelOptions(
            name='newpostregion',
            options={'ordering': ('description', 'description_ru'), 'verbose_name': 'Район', 'verbose_name_plural': '3. Районы'},
        ),
        migrations.AlterField(
            model_name='newpostapikey',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Ключ'),
        ),
    ]
