# Generated by Django 4.2.4 on 2023-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModnaKastaTolen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
