# Generated by Django 4.2.4 on 2023-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modnakastalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modnakastalog',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
