# Generated by Django 4.2.4 on 2023-11-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modnakastalog_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modnakastalog',
            old_name='data',
            new_name='date',
        ),
    ]
