# Generated by Django 4.2.4 on 2023-11-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_data_modnakastalog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModnaKastaLog',
        ),
        migrations.DeleteModel(
            name='ModnaKastaTolen',
        ),
    ]
