# Generated by Django 4.1.7 on 2023-04-29 15:53

import apps.abstract.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('image', 'Image'), ('mini_post', 'Mini Post')], max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', apps.abstract.fields.DeletableImageField(upload_to='home_slider/')),
                ('image_2', apps.abstract.fields.DeletableImageField(blank=True, null=True, upload_to='home_slider/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
            },
        ),
    ]
