# Generated by Django 4.1.7 on 2023-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Баннер домашней страницы', 'verbose_name_plural': 'Баннеры домашней страницы'},
        ),
        migrations.AddField(
            model_name='homeslider',
            name='link_type',
            field=models.CharField(choices=[('category', 'Категория'), ('collection', 'Коллекция'), ('product', 'Товар'), ('page', 'Страница')], default='category', max_length=255),
        ),
    ]
