# Generated by Django 4.1.7 on 2023-06-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_homeslider_options_homeslider_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
