# Generated by Django 4.2.1 on 2023-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_homeslider_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='link_type',
            field=models.CharField(choices=[('category', 'Категория'), ('collection', 'Коллекция'), ('product', 'Товар'), ('page', 'Страница')], default='category', max_length=255),
        ),
    ]
