# Generated by Django 4.2 on 2023-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_pages_title_remove_pagestranslation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslidertranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pagestranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
    ]
