# Generated by Django 4.2.1 on 2023-06-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homeslider_link_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='link',
        ),
    ]
