# Generated by Django 4.2.1 on 2023-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_homeslider_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
