# Generated by Django 4.2.1 on 2023-06-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_pages_title_remove_pagestranslation_title'),
        ('pages', '0007_homeslider_link'),
    ]

    operations = [
    ]
