# Generated by Django 4.2 on 2023-08-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_homeslidertranslation_language_code_and_more'),
        ('pages', '0008_merge_20230628_2005'),
    ]

    operations = [
    ]
