# Generated by Django 4.2.4 on 2023-09-19 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_homeslidertranslation_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pagestranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
