# Generated by Django 4.2.4 on 2023-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_pages_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
    ]
