import React from "react";
import Head from 'next/head'
import {Header} from "@/components/Shared/Header";
import CustomThemeProvider from "@/styles/ThemeProvider";
import {Footer} from "@/components/Shared/Footer";
import {usePathname} from 'next/navigation';
import Script from 'next/script'
import {Container, Main} from "@/components/Shared/LandingLayout/style";


interface LayoutProps {
    title?: string;
    children: React.ReactNode;
    data?: any
}

export default function Layout({children, title = 'Moami'}: LayoutProps) {
    const path = usePathname()

    return <>
        <Head>
            <title>Moami</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <CustomThemeProvider>
            <Script
                id="fb-pixel"
                strategy="afterInteractive"
                dangerouslySetInnerHTML={{
                    __html: `
                         !function(f,b,e,v,n,t,s)
                        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                        n.queue=[];t=b.createElement(e);t.async=!0;
                        t.src=v;s=b.getElementsByTagName(e)[0];
                        s.parentNode.insertBefore(t,s)}(window, document,'script',
                        'https://connect.facebook.net/en_US/fbevents.js');
                        fbq('init', '600334120449114');
                    `
                }}
            />
            <Main>
                <Container>
                     {children}
                </Container>
            </Main>
        </CustomThemeProvider>
    </>
}