# Generated by Django 4.1.7 on 2023-04-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_composition'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='attributes.composition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='product.product')),
            ],
        ),
    ]
