# Generated by Django 4.1.7 on 2023-04-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_composition'),
        ('product', '0002_productcomposition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomposition',
            unique_together={('product', 'composition')},
        ),
    ]
