# Generated by Django 4.1.7 on 2023-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcomposition_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomposition',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Составы'},
        ),
    ]
