# Generated by Django 4.1.7 on 2023-04-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcomposition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomposition',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Состав'},
        ),
    ]
