# Generated by Django 4.1.7 on 2023-04-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_alter_composition_slug'),
        ('product', '0005_alter_productcomposition_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.attributegroup')),
                ('attributes', models.ManyToManyField(to='attributes.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='VariantAttribute',
        ),
    ]
