# Generated by Django 4.1.7 on 2023-05-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_collection'),
        ('product', '0006_productattribute_delete_variantattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='categories.collection'),
        ),
    ]
