# Generated by Django 4.1.7 on 2023-05-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_rozetkacategories_slug'),
        ('product', '0011_alter_brand_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='integrations.googletaxonomy', verbose_name='Категория Google Taxonomy'),
        ),
    ]
