# Generated by Django 4.1.7 on 2023-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
