# Generated by Django 4.1.7 on 2023-06-11 12:26

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0004_alter_size_options_alter_sizegrid_options_and_more'),
        ('product', '0017_alter_variantimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=255, samples=None),
        ),
        migrations.AlterField(
            model_name='colortranslation',
            name='code',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=255, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_preferred_size_grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sizes.sizegrid', verbose_name='предпочтительная размерная сетка'),
        ),
    ]
