# Generated by Django 4.1.7 on 2023-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Обновления'),
        ),
    ]
