# Generated by Django 4.1.7 on 2023-06-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_index_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['index'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
