# Generated by Django 4.2 on 2023-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_updated_at_alter_variantimage_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_preferred_size_grid',
        ),
        migrations.AlterField(
            model_name='brandtranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='colortranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
    ]
