# Generated by Django 4.2 on 2023-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_product_preferred_size_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Акционная цена'),
        ),
    ]
