# Generated by Django 4.2 on 2023-08-30 15:18

import apps.abstract.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_variantvideo_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=apps.abstract.fields.DeletableVideoField(blank=True, null=True, upload_to='videos'),
        ),
    ]
