# Generated by Django 4.2.4 on 2023-09-06 20:08

import apps.abstract.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_variantimagethumbnail_exclude_at_marketplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=apps.abstract.fields.DeletableImageField(upload_to='variant_images', verbose_name='Файл'),
        ),
    ]
