# Generated by Django 4.2.4 on 2023-09-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_variantimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='product.variant')),
            ],
            options={
                'verbose_name': 'Просмотры',
                'verbose_name_plural': 'Просмотры',
            },
        ),
    ]
