# Generated by Django 4.2.4 on 2023-09-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_variantviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantviews',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='product.variant'),
        ),
    ]
