# Generated by Django 4.2.4 on 2023-09-19 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_variantviews_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='code',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Разрешенные символы 0-9, a-z, A-Z, -')]),
        ),
    ]
