# Generated by Django 4.2.4 on 2023-09-19 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0036_alter_variant_code_productcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComments',
            new_name='ProductComment',
        ),
    ]
