# Generated by Django 4.2.4 on 2023-09-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_productcommentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentimage',
            name='comment',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='ProductCommentImage',
        ),
    ]
