# Generated by Django 4.2.4 on 2023-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_productcomment_productcommentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='answer_to',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
