# Generated by Django 4.2.4 on 2023-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_rename_answer_to_productcomment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rozetka_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Rozetka'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='rozetka_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
