# Generated by Django 4.2.4 on 2023-10-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_product_rozetka_name_producttranslation_rozetka_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taxonomy',
        ),
    ]
