# Generated by Django 4.2.4 on 2023-10-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_variant_rozetka_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantviews',
            options={'ordering': ['variant', 'day'], 'verbose_name': 'Просмотры', 'verbose_name_plural': 'Просмотры'},
        ),
        migrations.AddField(
            model_name='variantviews',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='variantviews',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UTM Source'),
        ),
        migrations.AlterField(
            model_name='variantviews',
            name='day',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='variantviews',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
