# Generated by Django 4.2.4 on 2023-10-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_variantviews_options_variantviews_utm_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantviews',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='variantviews',
            name='utm_source',
        ),
        migrations.CreateModel(
            name='VarintViewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='UTM Source')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('variant_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_sources', to='product.variantviews')),
            ],
        ),
    ]
