# Generated by Django 4.2.4 on 2023-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_color_mk_id_colortranslation_mk_id_variantattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='mk_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='countrytranslation',
            name='mk_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
