# Generated by Django 4.2.4 on 2023-12-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0015_alter_attributegroup_data_type'),
        ('product', '0048_country_mk_id_countrytranslation_mk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attributes',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attribute'),
        ),
    ]
