# Generated by Django 4.2.4 on 2023-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_remove_productattribute_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
