# Generated by Django 4.2.4 on 2023-12-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0015_alter_attributegroup_data_type'),
        ('product', '0050_productattribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_int',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_multi_attributes',
            field=models.ManyToManyField(blank=True, related_name='multi_attr', to='attributes.attribute'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_single_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_attr', to='attributes.attribute'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
