# Generated by Django 4.2.4 on 2023-12-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0015_alter_attributegroup_data_type'),
        ('product', '0051_remove_productattribute_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_group', to='attributes.attributegroup', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_multi_attributes',
            field=models.ManyToManyField(blank=True, related_name='multi_attr', to='attributes.attribute', verbose_name='Множественный выбор'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_single_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_attr', to='attributes.attribute', verbose_name='Единичный выбор'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Строка'),
        ),
    ]
