# Generated by Django 4.2.4 on 2023-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_productattribute_attribute_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mk_attributes_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mk_attributes_copy_to',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
