# Generated by Django 4.2.4 on 2023-12-06 22:45

import apps.abstract.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('product', '0055_alter_product_mk_attributes_copy_and_more'), ('product', '0056_alter_variantalterimage_thumbnails'), ('product', '0057_remove_variantimage_slug_variantimage_thumbnails_and_more'), ('product', '0058_alter_variantimage_image'), ('product', '0059_delete_variantalterimage')]

    dependencies = [
        ('product', '0054_alter_variantimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mk_attributes_copy',
            field=models.BooleanField(default=False, verbose_name='Применить копирование аттрибутов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mk_attributes_copy_to',
            field=models.ManyToManyField(blank=True, help_text='Список товаров из тойже категории в которые будет осуществлено копирование выбранных атрибутов Модна Каста', to='product.product', verbose_name='Скопировать набор атрибутов в товары'),
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='slug',
        ),
        migrations.AddField(
            model_name='variantimage',
            name='thumbnails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='variantimagethumbnail',
            name='variant_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_thumbnails', to='product.variantimage'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=apps.abstract.models.ImageField(upload_to=''),
        ),
    ]
