# Generated by Django 4.2.4 on 2023-12-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_product_mk_attributes_copy_and_more_squashed_0059_delete_variantalterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantMkUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('response', models.JSONField(blank=True, default=dict, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.variant')),
            ],
        ),
    ]
