# Generated by Django 4.2.4 on 2023-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_variantmkupdatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='color',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
    ]
