# Generated by Django 4.2.4 on 2024-01-31 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0008_remove_sizegroup_mk_id'),
        ('product', '0061_brand_auto_translate_color_auto_translate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsize',
            name='max_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_sizes', to='sizes.size'),
        ),
    ]
