# Generated by Django 4.2 on 2024-08-03 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_variantsize_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='extra_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
