# Generated by Django 4.2 on 2025-06-06 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_product_extra_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Разрешенные символы 0-9, a-z, A-Z, -')], verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
