# Generated by Django 4.2 on 2025-09-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_epicentrproductattribute'),
        ('product', '0064_product_code_producttranslation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='epicentr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='integrations.epicentrcategories', verbose_name='Категория Epicentr'),
        ),
    ]
