# Generated by Django 4.2 on 2025-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_product_epicentr_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='epicentr_category',
        ),
    ]
