# Generated by Django 4.1.7 on 2023-04-29 16:15

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='GoogleTaxonomy',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('name_ru', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Категории: категория Google Taxonomy',
                'verbose_name_plural': 'Категории: категории Google Taxonomy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleTaxonomyUplaoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.FileField(help_text='.xlsx', upload_to='google_taxonomy')),
                ('table_ru', models.FileField(help_text='.xlsx', upload_to='google_taxonomy')),
                ('delate_all', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Загрузчик: категория Google Taxonomy',
                'verbose_name_plural': 'Загрузчик: категории Google Taxonomy',
            },
        ),
        migrations.CreateModel(
            name='RozetkaCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='integrations.rozetkacategories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
