# Generated by Django 4.1.7 on 2023-06-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_rozetkacategories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozetkacategories',
            name='rozetka_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
