# Generated by Django 4.1.7 on 2023-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_rozetkacategories_rozetka_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rozetkacategories',
            options={'verbose_name': 'Категория Rozetka', 'verbose_name_plural': 'Категории Rozetka'},
        ),
        migrations.AlterField(
            model_name='rozetkacategories',
            name='rozetka_id',
            field=models.PositiveIntegerField(),
        ),
    ]
