# Generated by Django 4.2.4 on 2023-09-26 09:48

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_googletaxonomy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletaxonomyuplaoder',
            name='table',
            field=models.FileField(help_text='.txt', upload_to='google_taxonomy', validators=[apps.integrations.models.validate_txt], verbose_name='Таблица на английском (.txt)'),
        ),
        migrations.AlterField(
            model_name='googletaxonomyuplaoder',
            name='table_ru',
            field=models.FileField(help_text='.txt', upload_to='google_taxonomy', validators=[apps.integrations.models.validate_txt], verbose_name='Таблица на английском (.txt)'),
        ),
    ]
