# Generated by Django 4.2.4 on 2023-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_googletaxonomy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletaxonomy',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
