# Generated by Django 4.2.4 on 2023-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_googletaxonomy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletaxonomy',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
