# Generated by Django 4.2.4 on 2023-09-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_alter_googletaxonomy_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletaxonomyuplaoder',
            name='filter_root',
            field=models.CharField(blank=True, default='Apparel & Accessories', max_length=1000, null=True),
        ),
    ]
