# Generated by Django 4.2.4 on 2023-10-08 15:11

import apps.integrations.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_rozetkaadaptation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookСategoriesLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.FileField(help_text='.csv', upload_to='facebook_categories', validators=[apps.integrations.models.validate_txt], verbose_name='Таблица со списком категорий (.csv)')),
                ('filter_root', models.CharField(blank=True, default='clothing & accessories', max_length=1000, null=True)),
                ('delete_all', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Загрузчик: категория Facebook',
                'verbose_name_plural': '6. Загрузчик: категории Facebook',
            },
        ),
        migrations.AlterModelOptions(
            name='googletaxonomy',
            options={'ordering': ['name'], 'verbose_name': 'Категории: категория Google Taxonomy', 'verbose_name_plural': '3. Категории: категории Google Taxonomy'},
        ),
        migrations.AlterModelOptions(
            name='googletaxonomyuplaoder',
            options={'verbose_name': 'Загрузчик: категория Google Taxonomy', 'verbose_name_plural': '4. Загрузчик: категории Google Taxonomy'},
        ),
        migrations.AlterModelOptions(
            name='rozetkaadaptation',
            options={'verbose_name': 'Адаптация Rozetka', 'verbose_name_plural': '2. Адаптация Rozetka'},
        ),
        migrations.CreateModel(
            name='FacebookCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook_id', models.CharField(max_length=24)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='integrations.facebookcategories')),
            ],
            options={
                'verbose_name': 'Категория Facebook',
                'verbose_name_plural': '5. Категории Facebook',
            },
        ),
    ]
