# Generated by Django 4.2.4 on 2023-10-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_facebookсategoriesloader_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookСategoriesLoader',
            new_name='FacebookCategoriesLoader',
        ),
    ]
