# Generated by Django 4.2.4 on 2023-10-08 15:15

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_rename_facebookсategoriesloader_facebookcategoriesloader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcategoriesloader',
            name='table',
            field=models.FileField(help_text='.csv', upload_to='facebook_categories', validators=[apps.integrations.models.validate_csv], verbose_name='Таблица со списком категорий (.csv)'),
        ),
    ]
