# Generated by Django 4.2.4 on 2023-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_alter_facebookcategoriesloader_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookcategories',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
