# Generated by Django 4.2.4 on 2023-11-28 21:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_modnakastalog_modnakastatolen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModnaKastaCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_alias', models.CharField(max_length=128)),
                ('kind_id', models.PositiveIntegerField(default=0)),
                ('affiliation_id', models.PositiveIntegerField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='integrations.modnakastacategories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
