# Generated by Django 4.2.4 on 2023-12-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_modnakastacategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modnakastacategories',
            options={'verbose_name': '8. Модна Каста: Категории', 'verbose_name_plural': '8. Модна Каста: Категории'},
        ),
        migrations.AlterModelOptions(
            name='modnakastalog',
            options={'verbose_name': '9. Модна Каста: Лог', 'verbose_name_plural': '9. Модна Каста: Лог'},
        ),
        migrations.AlterModelOptions(
            name='modnakastatolen',
            options={'verbose_name': '7. Модна Каста: Токен ', 'verbose_name_plural': '7. Модна Каста: Токен'},
        ),
    ]
