# Generated by Django 4.2 on 2025-09-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_alter_modnakastacategories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicentrAttributeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EpicentrCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('attribute_sets', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='EpicentrAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('attribute_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='integrations.epicentrattributeset')),
            ],
        ),
    ]
