# Generated by Django 4.2 on 2025-09-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_epicentrattributeset_epicentrcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicentrattribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epicentrattribute',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epicentrattribute',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='EpicentrAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='integrations.epicentrattribute')),
            ],
        ),
        migrations.CreateModel(
            name='EpicentrAttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('attribute_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_groups', to='integrations.epicentrattributeset')),
            ],
        ),
        migrations.AddField(
            model_name='epicentrattribute',
            name='attribute_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='integrations.epicentrattributegroup'),
        ),
    ]
