# Generated by Django 4.2 on 2025-09-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_product_code_producttranslation_code'),
        ('integrations', '0021_epicentrattribute_is_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicentrProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=512, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_array', models.JSONField(blank=True, default=list)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='integrations.epicentrattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epicentr_attributes', to='product.product')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_values', to='integrations.epicentrattributeoption')),
                ('value_options', models.ManyToManyField(blank=True, related_name='product_multi_values', to='integrations.epicentrattributeoption')),
            ],
            options={
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
