# Generated by Django 4.2 on 2025-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0025_remove_category_epicentr_category'),
        ('product', '0066_remove_product_epicentr_category'),
        ('integrations', '0022_epicentrproductattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epicentrattribute',
            name='attribute_group',
        ),
        migrations.RemoveField(
            model_name='epicentrattribute',
            name='attribute_set',
        ),
        migrations.RemoveField(
            model_name='epicentrattributegroup',
            name='attribute_set',
        ),
        migrations.RemoveField(
            model_name='epicentrattributeoption',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='EpicentrCategories',
        ),
        migrations.AlterUniqueTogether(
            name='epicentrproductattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='epicentrproductattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='epicentrproductattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='epicentrproductattribute',
            name='value_option',
        ),
        migrations.RemoveField(
            model_name='epicentrproductattribute',
            name='value_options',
        ),
        migrations.DeleteModel(
            name='EpicentrAttribute',
        ),
        migrations.DeleteModel(
            name='EpicentrAttributeGroup',
        ),
        migrations.DeleteModel(
            name='EpicentrAttributeOption',
        ),
        migrations.DeleteModel(
            name='EpicentrAttributeSet',
        ),
        migrations.DeleteModel(
            name='EpicentrProductAttribute',
        ),
    ]
