# Generated by Django 4.1.7 on 2023-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
