# Generated by Django 4.1.7 on 2023-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_alter_composition_name_alter_composition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
