# Generated by Django 4.1.7 on 2023-05-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0006_alter_attribute_slug_alter_attributegroup_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='attributegroup',
            options={'verbose_name': 'Группа атрибутов', 'verbose_name_plural': 'Группы атрибутов'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Состав'},
        ),
    ]
