# Generated by Django 4.1.7 on 2023-05-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_alter_attribute_options_alter_attributegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(choices=[('uk-ua', 'Ukrainian'), ('en-us', 'English')], max_length=6)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='attributes.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(choices=[('uk-ua', 'Ukrainian'), ('en-us', 'English')], max_length=6)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='attributes.attributegroup')),
            ],
        ),
    ]
