# Generated by Django 4.1.7 on 2023-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_alter_composition_name_compositiontranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegrouptranslation',
            name='language_code',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='attributetranslation',
            name='language_code',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='compositiontranslation',
            name='language_code',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], max_length=6),
        ),
    ]
