# Generated by Django 4.1.7 on 2023-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0010_alter_attributegrouptranslation_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='compositiontranslation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
