# Generated by Django 4.2 on 2023-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0011_alter_attribute_name_alter_attributegroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegrouptranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='attributetranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='compositiontranslation',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=6),
        ),
    ]
