# Generated by Django 4.2.4 on 2023-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0013_alter_attributegrouptranslation_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='mk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='data_type',
            field=models.CharField(choices=[('multi_attr', 'multi_attr'), ('single_attr', 'single'), ('integer', 'integer'), ('sting', 'sting')], default=('multi_attr', 'multi_attr'), max_length=50),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='mk_key_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='mk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributegrouptranslation',
            name='data_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributegrouptranslation',
            name='mk_key_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributegrouptranslation',
            name='mk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributetranslation',
            name='mk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
