# Generated by Django 4.2.4 on 2023-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0014_attribute_mk_id_attributegroup_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegroup',
            name='data_type',
            field=models.CharField(choices=[('multi_attr', 'multi_attr'), ('single_attr', 'single'), ('integer', 'integer'), ('sting', 'sting')], default='multi_attr', max_length=50),
        ),
    ]
