# Generated by Django 4.2.4 on 2023-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0015_alter_attributegroup_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegroup',
            name='data_type',
            field=models.CharField(choices=[('multi_attr', 'Множественный выбор'), ('single_attr', 'Единичный выбор'), ('integer', 'Число'), ('sting', 'Строка')], default='multi_attr', max_length=50),
        ),
    ]
