# Generated by Django 4.2.4 on 2023-12-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0016_alter_attributegroup_data_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributegroup',
            options={'ordering': ('name',), 'verbose_name': 'Группа атрибутов', 'verbose_name_plural': 'Группы атрибутов'},
        ),
    ]
