# Generated by Django 4.2 on 2023-12-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0017_alter_attributegroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('name',), 'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
    ]
