# Generated by Django 4.2.4 on 2023-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0017_alter_attributegroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('name',), 'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
