# Generated by Django 4.2 on 2023-12-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0018_alter_attribute_options'),
        ('attributes', '0018_alter_attribute_options_alter_attribute_slug_and_more'),
    ]

    operations = [
    ]
