# Generated by Django 4.2.4 on 2023-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0018_alter_attribute_options_alter_attribute_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
    ]
