# Generated by Django 4.2 on 2023-12-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0019_attribute_auto_translate_and_more'),
        ('attributes', '0019_merge_20231213_1536'),
    ]

    operations = [
    ]
