# Generated by Django 4.2.4 on 2024-01-31 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_alter_modnakastacategories_options_and_more'),
        ('attributes', '0020_merge_20231213_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeInModnaKastaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.attribute')),
                ('mk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.modnakastacategories')),
            ],
        ),
    ]
