# Generated by Django 4.2.4 on 2024-01-31 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0021_attributeinmodnakastacategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeinmodnakastacategory',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mk_categories', to='attributes.attribute'),
        ),
    ]
