# Generated by Django 4.2 on 2023-08-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdelivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='comment',
        ),
    ]
