# Generated by Django 4.2 on 2023-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderdelivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
