# Generated by Django 4.2 on 2023-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderdelivery_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryaddress',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.orderdelivery', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='orderdeliverynewpost',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newpost', to='order.orderdelivery', verbose_name='Доставка'),
        ),
    ]
