# Generated by Django 4.2 on 2023-08-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0002_alter_newpostapikey_options_and_more'),
        ('order', '0006_alter_orderdeliveryaddress_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverynewpost',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostareas', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='orderdeliverynewpost',
            name='city',
            field=models.ForeignKey(default='Киев', on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostcities', verbose_name='Город'),
        ),
    ]
