# Generated by Django 4.2 on 2023-08-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderdeliveryaddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryaddress',
            name='city',
            field=models.CharField(blank=True, default='Киев', max_length=100, null=True, verbose_name='Город'),
        ),
    ]
