# Generated by Django 4.2 on 2023-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderdeliveryaddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_type',
            field=models.CharField(choices=[('address', 'Курьером по Киеву'), ('newpost', 'Новая почта'), ('other', 'Другое')], max_length=100, verbose_name='Тип доставки'),
        ),
    ]
