# Generated by Django 4.2 on 2025-06-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0002_alter_newpostapikey_options_and_more'),
        ('order', '0012_alter_order_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverynewpost',
            name='city_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город (текст)'),
        ),
        migrations.AddField(
            model_name='orderdeliverynewpost',
            name='warehouse_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Склад (текст)'),
        ),
        migrations.AlterField(
            model_name='orderdeliverynewpost',
            name='city',
            field=models.ForeignKey(blank=True, default='Киев', null=True, on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostcities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='orderdeliverynewpost',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostdepartments', verbose_name='Отделение'),
        ),
    ]
