# Generated by Django 4.2 on 2025-06-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0002_alter_newpostapikey_options_and_more'),
        ('order', '0013_orderdeliverynewpost_city_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliverynewpost',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostcities', verbose_name='Город'),
        ),
    ]
