# Generated by Django 4.1.7 on 2023-04-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='SizeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('base_grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_grid', to='sizes.sizegrid')),
                ('grids', models.ManyToManyField(related_name='groups', to='sizes.sizegrid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SizeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('size_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='sizes.sizegroup')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SizePropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sizes.sizeproperty')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='sizes.size')),
            ],
        ),
        migrations.CreateModel(
            name='SizeInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='sizes.sizegrid')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='sizes.size')),
            ],
            options={
                'ordering': ['grid__order'],
            },
        ),
        migrations.AddField(
            model_name='size',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='sizes.sizegroup'),
        ),
    ]
