# Generated by Django 4.1.7 on 2023-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0002_alter_sizegrid_slug_alter_sizegroup_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeproperty',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
