# Generated by Django 4.2.4 on 2023-09-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0004_alter_size_options_alter_sizegrid_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizegroup',
            name='base_grid',
        ),
    ]
