# Generated by Django 4.2.4 on 2023-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0005_remove_sizegroup_base_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='mk_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
