# Generated by Django 4.2.4 on 2023-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0006_size_mk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizegroup',
            name='mk_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='mk_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
