# Generated by Django 4.2 on 2025-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0008_remove_sizegroup_mk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizegroup',
            name='grids',
            field=models.ManyToManyField(blank=True, related_name='groups', to='sizes.sizegrid'),
        ),
    ]
